apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openopt-riskengine

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: openopt-riskengine
  app.kubernetes.io/managed-by: kubectl
