apiVersion: v1
kind: Service
metadata:
  name: openopt-riskengine-service
  namespace: openopt-riskengine
  labels:
    app: openopt-riskengine
spec:
  type: LoadBalancer
  selector:
    app: openopt-riskengine
    component: webapp
  ports:
    - port: 80
      targetPort: 8501
      protocol: TCP
      name: http
